apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end
  name: website-app
  namespace: dev

spec:
  replicas: 4
  selector:
    matchLabels:
      app: front-end

  template:
    metadata:
      labels:
        app: front-end

    spec:
      containers:
      - image: nginx
        name: nginx
