apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: db-tier
  name: dev-db
  namespace: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      type: db-tier

  template:
    metadata:
      labels:
        type: db-tier

    spec:
      containers:
      - image: redis
        name: redis
