apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: backend-end
  name: website1-app
  namespace: dev

spec:
  replicas: 6
  selector:
    matchLabels:
      type: front-end

  template:
    metadata:
      labels:
        type: front-end

    spec:
      containers:
      - image: nginx
        name: nginx
