apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: backend-end
  name: web-app2
  namespace: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end

  template:
    metadata:
      labels:
        type: front-end

    spec:
      containers:
      - image: tomcat:8-jdk11-corretto
        name: tomcat
