apiVersion: v1
kind: Pod
metadata:
  labels:
    app: front-end
    type: webapp
  name: mypod1
spec:
  containers:
  - image: nginx
    name: mypod1


  volumes:
   - name: nginx-config-volume
        configMap:
          name: nginx-configmap
