apiVersion: v1
kind: Pod
metadata:
  labels:
    app: front-end
    type: webapp
  name: mypod2
spec:
  containers:
  - image: nginx
    name: mypod2
    envFrom:
       - configMapRef:
          name: nginx-configmap
         
