apiVersion: v1
kind: Service
metadata:
    name: back-end
    namespace: dev

spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      name: nginx
    - targetPort: 8080
      port: 8080
      name: tomcat
  selector:
      type: back-end

