apiVersion: v1
kind: Service
metadata:
   name: front-end
   namespace: dev

spec:
   type: NodePort
   ports:
     - targetPort: 80
       port: 8080
       nodePort: 30001
   selector:
       type: front-end       
