apiVersion: v1
kind: Service
metadata:
   name: front-end
   namespace: dev
 
spec:
   type: NodePort
   ports:
     - targetPort: 80
       port: 80
       name: nginx
       nodePort: 30001

     - targetPort: 8080
       port: 8080
       name: tomecat
       nodePort: 30002 
   selector:
       type: front-end       
