apiVersion: v1
kind: Service
metadata:
   name: deployment-service
   namespace: dev

spec:
    type: NodePort
    ports:
      - targetPort: 80
        port: 8080
        nodePort: 30010
 
    selector:
       app: front-end
