apiVersion: v1
kind: Pod
metadata:
  name: httpd-on-node1
  labels:
     app: webapp
     tier: frontend
  annotations:
     email: ulrichoke@gmail.com
     build: v1.0.1
spec:
   nodeName: node1
   containers:
   - image: httpd
     name: apache2
