apiVersion: v1
kind: Pod
metadata:
  labels:
    app: front-end
    type: webapp
  name: mypod1
spec:
  containers:
  - image: nginx
    name: mypod1
    env:
       - name: APP1_DB_USER_VAR
         valueFrom:
            secretKeyRef:
                  name: secret-def-1
                  key: APP1_DB_USER_VAR
       - name: APP1_DB_PASSWD_VAR
         valueFrom:
            secretKeyRef:
                  name: secret-def-1
                  key: APP1_DB_PASSWD_VAR
         
